name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        versions:
          - python: "3.10"
            toxenv: py310-4.2.X
          - python: "3.11"
            toxenv: py311-4.2.X

          - python: "3.10"
            toxenv: py310-5.1.X
          - python: "3.11"
            toxenv: py311-5.1.X
          - python: "3.12"
            toxenv: py312-5.1.X
          - python: "3.13"
            toxenv: py313-5.1.X

          - python: "3.10"
            toxenv: py310-5.2.X
          - python: "3.11"
            toxenv: py311-5.2.X
          - python: "3.12"
            toxenv: py312-5.2.X
          - python: "3.13"
            toxenv: py313-5.2.X
          - python: "3.14"
            toxenv: py314-5.2.X

          - python: "3.12"
            toxenv: py312-6.0.X
          - python: "3.13"
            toxenv: py313-6.0.X
          - python: "3.14"
            toxenv: py314-6.0.X

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.versions.python }}
      - run: |
          pip install tox
      - run: tox -e ${{ matrix.versions.toxenv }}
      - run: |
          pip install codecov
          codecov
